name: CI

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.19

      - name: Install dependencies
        run: bun install --frozen-lockfile

      # You can either use the setup-biome action or your devDependency via bunx.
      # A1) First-party action:
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome (GitHub annotations)
        run: biome ci --reporter=github .

      # OR A2) Use your devDependency instead of setup-biome:
      # - name: Run Biome (from devDeps)
      #   run: bunx @biomejs/biome ci --reporter=github .

  # Optional extra jobs (parallel)
  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.19
      - run: bun install --frozen-lockfile
      - name: Type check
        run: bun run check-types

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.19
      - run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
